name: Python CI (non-failing)

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: Syntax & Lint (non-failing)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python syntax check (non-failing)
        shell: bash
        run: |
          set -e
          pyfiles="$(git ls-files '*.py' || true)"
          if [ -z "$pyfiles" ]; then
            echo "No Python files found. Skipping syntax check."
          else
            # Do not fail the job even if there are syntax errors
            python -m py_compile $pyfiles || echo "Syntax errors found (ignored for now)."
          fi

      - name: Ruff lint (non-failing)
        shell: bash
        run: |
          pyfiles="$(git ls-files '*.py' || true)"
          if [ -z "$pyfiles" ]; then
            echo "No Python files found. Skipping Ruff."
          else
            pip install --quiet ruff
            # Do not fail the job even if Ruff reports issues
            ruff check --output-format=github . || echo "Ruff reported issues (ignored for now)."
          fi

      - name: CI finished
        run: echo "✅ CI completed successfully (non-failing mode)."
